language:
    cpp

os:
    linux

addons:
    apt:
        packages:
            - g++-5
            - gcc-5

        sources:
            - ubuntu-toolchain-r-test

before_install:
    - export CC=gcc-5
    - export CXX=g++-5
    - export LD_LIBRARY_PATH=/usr/local/lib
    
    - wget https://www.libsdl.org/release/SDL2-2.0.4.tar.gz
    - tar -xf SDL2-2.0.4.tar.gz
    
    - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
    - tar -xf SDL2_image-2.0.1.tar.gz 
    
    - git clone https://github.com/google/googletest.git
    
install:
    - mkdir -p SDL2-2.0.4/build
    - pushd SDL2-2.0.4/build
    - cmake ../ && make -j4 && sudo make install
    - popd
    
    - pushd SDL2_image-2.0.1
    - ./configure && make -j4 && sudo make install 
    - popd
    
    - mkdir -p googletest/build 
    - pushd googletest/build
    - cmake ../ && make -j4 && sudo make install
    - popd

script:
    - mkdir build && cd build
    - cmake -Dtest=ON ../ && make
    - ctest -V

notifications:
    email:
        on_success: never
        on_failure: never
    
